name: Connect Four
on:
  issues:
    types: [opened]

jobs:
  move:
    runs-on: ubuntu-latest
    steps:
      - uses: JonathanGin42/connect-four@v1.4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
